### ISSUE TITLE
USER STORY: User Login & Logout

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Project-4-CodeInstitute#1]
As a **User**, I can log in or log out of my account so that I can keep my account secure.

**Acceptance Criteria:**
1. Sign in button should be visible on the home page and on the nav bar.
2. When I click the button I should be taken to the log-in page.
3. When I fill in my details and click submit I should be logged in.
4. I should then be notified that I have been logged in successfully.
5. If I enter the incorrect credentials I should receive feedback on what information was incorrectly entered.
6. When I click the log out button I should be asked to confirm I want to log out.
7. When I confirm I wish to log out I should be notified that I have been logged out successfully.

**Tasks**
- [x]  Install allauth and add to installed apps
- [x]  Add allauth urls
- [x]  Add log in and log out links to navbar
- [x]  Customise allauth login, logout HTML templates
- [x]  Create success messages for successful login/logout
