### ISSUE TITLE
USER STORY: Favourite Posts

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Project-4-CodeInstitute#10]
As a **User**, I can save other users' post to my favourites so I can find them easily at a later date.

**Acceptance Criteria:**
1. When a user is logged in, a favourite icon should display in the post detail view for each post.
2. When the user clicks on the icon it should toggle the favourites by adding or removing from the user's favourites page.
3. The icon should toggle its UI based on its favourites status.

**Tasks**

- [ ] Create a favourite button on the recipe detail page that only appears when the user is logged in.
- [ ] Create FavouritePost view function that adds/removes user ID from favourites field of each recipe when the button is clicked.
- [ ] Change favourite icon to solid when user had favourited it.
