### ISSUE TITLE
USER STORY: Profile Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Project-4-CodeInstitute#12]
As a **User**, I can visit my profile page so that I can edit my details if needed.

**Acceptance Criteria:**
1. Users when logged in can navigate to their profile page
2. Users can view their current information
3. Users can navigate update settings by selecting a button
4. Users posts, total comments, likes and favourites are viewable
5. Users can navigate to their posts for editing

**Tasks**
- [x] Add navigation to profile page when logged in
- [x] Create A Profile page view and template
- [x] Render current authenticated information in the template
- [x] Allow users to update information by clicking edit settings if authenticated
- [x] Users total favourites, posts, likes and comments are rendered
- [x] A user can navigate to their posts of profile pag
