### ISSUE TITLE
USER STORY: Update Profile Information

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Project-4-CodeInstitute#13]
As a **User**, I can update my Profile page so can keep my information up to date and accurate.

**Acceptance Criteria:**
1. A user can navigate to an update profile page
2. A user can update their basic information and password
3. A user can only update their account information
4. A user can delete their account

**Tasks**
- [x] Create nn update user view
- [x] Create an update user template
- [x] Create user and password update forms
- [x] Update urls to route to template
- [x] Create update messages upon success
- [x] Push validation errors to ui on invalid forms
- [x] Create a delete user function to remove users from DB
