### ISSUE TITLE
USER STORY: Post Details Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Project-4-CodeInstitute#14]
As a **User**, I can view blog posts and associated information so that I can read, comment, like, favourite, or view other authors work.

**Acceptance Criteria:**
1. A user can browse through categories and visit the details of selected post
2. A user can view the comments and statistics details of a post
3. A user can see related posts in a siderbar
4. A user can see the publication author and date

**Tasks**
- [x] Create A post detail html template
- [x] Render post content, title and publish date
- [x] Link the authors profile page to template
- [x] Render all comments, likes and favourites to post
- [x] Display related posts in a sidebar
