### ISSUE TITLE
USER STORY: New User Registration

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Project-4-CodeInstitute#2]
As a **User**,  I can register an account so that I can favourite/add/edit/delete posts and comments.

**Acceptance Criteria:**
1. A signup button should be visible on the homepage.
2. When I click the button I should be taken to the signup page.
3. When I fill in my details and click submit a new account should be created for me.
4. I should then be notified that I have been logged in.

**Tasks**
- [x]  Install allauth and add to installed apps
- [x]  Add allauth urls
- [x]  Add signup link to navbar and home page
- [x] Customise allauth signup form HTML templates
- [x] Create message to notify user of successful signup
