### ISSUE TITLE
USER STORY: Add Post

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Project-4-CodeInstitute#3]
As a **User**, I can create post through an easy-to-use interface so that I can share them with other users.

**Acceptance Criteria:**
1. When a user is logged in, a create post button should appear on the home page and in the navbar.
2. When the user clicks the button, the user should be taken to the add post form.
3. When the user fills in the required information and clicks submit, the new post should be set to pending. 
4. The user should be notified that the recipe has been created successfully.
5. If the user fills in the form incorrectly they should be informed why the form won't submit.

**Tasks**
- [x] Create Post Form in forms.py
- [x] Create a Post model in models.py
- [x] Install summernote package of post creation.
- [x] Create AddPost Class in views.py
- [x] Create an intuitive post user input form
- [x] Develop validation for the post form to ensure correct information is included
- [x] Render add post templates
- [x] Create a success message for adding a post
