### ISSUE TITLE
USER STORY: Comment/Like Posts

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Project-4-CodeInstitute#5]
As a **User**, I can comment and like other people's posts so I can give feedback.

**Acceptance Criteria:**
1. When a user is logged in, a comment form should display on the recipe detail page below the post.
2. 1. When a user is logged in, a like button should appear below the post.
3. When the user fills in the form and clicks submit, the new comment should be set to pending.
4. UI is given when an action is completed

**Tasks**
- [x]  Create comment form class in forms.py
- [x]  Add comment form to post detail view and write get and post methods.
- [x]  Add user input form to post detail HTML template.
- [x]  Add a like button increments the like count
- [x] Create UI feedback notification when a comment is pending
