### ISSUE TITLE
USER STORY: Browse Categories

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Project-4-CodeInstitute#6]
As a **User**,I can view a list of categories and related posts so that I can select a post to view.

**Acceptance Criteria:**
1. When the user navigates to the home page  they are presented with a list of all categories from the database.
2. Depending on the selected category a list of post summary cards is rendered
3. When the user click on an individual post they are taken to the full post details.

**Tasks**
- [x] Create CategoryList class in views.py to list all categories in database.
- [x] Create browse categories HTML template
- [x] Render related posts depending on category selection to template
- [x] Develop a user-friendly summary post card layout.
- [x] Link post cards to post detail page.
- [x] Add pagination if there is over 10 results
