### ISSUE TITLE
USER STORY: Content Moderation

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/Project-4-CodeInstitute#8]
As a **Site Admin**, I can approve/create/edit/delete post so that I can moderate the sites content to be PG

**Acceptance Criteria:**
1. When the admin user is logged into the admin panel they can see a list of all post and comments
2. The admin user can delete and edit any post or across the site.
3. The admin user can create new posts or comments
4. The admin user must approve and comment or post before it is published

**Tasks**
- [x] Create a superuser. 
- [x] Set up Post and Comment models on admin site
- [x] Create an approval checkbox for pending posts
- [x] Create an approval checkbox for pending comments
